services:
  localstack:
    networks:
      - vellora_network
    image: localstack/localstack-pro
    container_name: localstack
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=s3,sqs,lambda,rds,cloudfront,ses # weâ€™ll add sqs/lambda later
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_HOST=localhost.localstack.cloud
    ports:
      - "4566:4566" # LocalStack edge endpoint
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "./init-resources.sh:/etc/localstack/init/ready.d/init-resources.sh"
  postgres:
    networks:
      - vellora_network
    image: postgres:17.4
    container_name: vellora_postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Vellora
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  backend:
    networks:
      - vellora_network
    build:
      context: ./backend # Points to the backend folder
      dockerfile: Dockerfile
    container_name: vellora_backend_service
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FERNET_KEY=${FERNET_KEY}
      - OAUTH_PROVIDERS__GOOGLE__CLIENT_ID=${OAUTH_PROVIDERS__GOOGLE__CLIENT_ID}
      - OAUTH_PROVIDERS__GOOGLE__CLIENT_SECRET=${OAUTH_PROVIDERS__GOOGLE__CLIENT_SECRET}
      - OAUTH_PROVIDERS__GOOGLE__REDIRECT_URI=${OAUTH_PROVIDERS__GOOGLE__REDIRECT_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - OAUTH_PROVIDERS__GOOGLE__SCOPES=${OAUTH_PROVIDERS__GOOGLE__SCOPES}
      - OAUTH_STATE_TTL_SECONDS=${OAUTH_STATE_TTL_SECONDS}

  frontend:
    networks:
      - vellora_network
    build:
      context: ./frontend/Vellora # Points to the frontend folder
      dockerfile: Dockerfile
    container_name: vellora_frontend_service
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    depends_on:
      - backend
    command: ["npx", "expo", "start", "--tunnel"]
    stdin_open: true
    tty: true

volumes:
  postgres_data:

networks:
  vellora_network:
    name: vellora_network